import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='text 2xl bg-blue-200 text-blue-600 h-full'>
        {/* header */}
        <div className='bg-red-200 grid p-5 grid-cols-2 justify-between '>
          <h1>logo</h1>
          <div className='flex flex-wrap  justify-end  bg-green-200'>
            <div className='pr-10'>ico</div>
            <div className='pr-10'>singiin</div>
            <div className=''>singiup</div>
          </div>
        </div>
        {/* one */}
        <div className='bg-red-300 mt-40 m-5 text-center  grid h-1/3 grid-cols-4 gap-10 p-20 '>
          <div className='bg-gray-200'>one</div>
          <div className=' bg-green-200'>tow</div>
          <div className='bg-slate-200'>three</div>
          <div className='bg-green-200'>four</div>
        </div>
        
        {/* two */}
        <div className='m-5 mt-40'>
          <div className='bg-gray-200 mt-10 p-10'>one</div>
          <div className=' bg-green-200 mt-10 p-10'>tow</div>
          <div className='bg-slate-200 mt-10 p-10'>three</div>
          <div className='bg-green-200 mt-10 p-10'>four</div>
        </div>
        {/* img */}
        <div className=' m-40 text-center' >
          <Image  src='/1.jpg' layout='fixed' width={'1000px'} height='500px' />
        </div>
        {/* three */}
        <div className='m-5 mt-40'>
          <div className='bg-gray-200 mt-10 p-10'>one</div>
          <div className=' bg-green-200 mt-10 p-10'>tow</div>
          <div className='bg-slate-200 mt-10 p-10'>three</div>
          <div className='bg-green-200 mt-10 p-10'>four</div>
        </div>
        {/* four */}
        <div className='bg-red-300 mt-40 m-5 text-center  grid h-1/3 grid-cols-4 gap-10 p-20 '>
          <div className='bg-gray-200'>one</div>
          <div className=' bg-green-200'>tow</div>
          <div className='bg-slate-200'>three</div>
          <div className='bg-green-200'>four</div>
        </div>
        {/* img2 */}
        <div className=' m-40 text-center' >
          <Image  src='/1.jpg' layout='fixed' width={'1000px'} height='500px' />
        </div>
        {/* footer */}
        <div className='m-5 mt-40'>
          <div className='bg-gray-200 mt-10 p-10'>one</div>
          <div className=' bg-green-200 mt-10 p-10'>tow</div>
          <div className='bg-slate-200 mt-10 p-10'>three</div>
          <div className='bg-green-200 mt-10 p-10'>four</div>
        </div>
      </main>
      <footer className='text-center p-2'>footer</footer>
    </div>
  )
}

export default Home
