import { AnimatePresence, motion } from 'framer-motion'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Tab } from '../components/tab'


const Home: NextPage = () => {
  const [images, setimges] = useState(null)
  useEffect(() => {
    const fetchImages = async () => {
      const data = await fetch('https://jsonplaceholder.typicode.com/photos')
      const json = await data.json()
      setimges(json.slice(0, 10))
    }
    fetchImages()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='text 2xl bg-blue-200 text-blue-600 h-full'>
        {/* header */}
        <motion.div
          transition={{ ease: 'easeOut', duration: 2 }}
          animate={{ x: [100,50,40,30, 20, 10], y: [100, 50,40,30,10], opacity: 1 }}
          className='bg-red-200 grid p-5 grid-cols-2 justify-between '
        >
          <h1>logo</h1>
          <motion.div className='flex flex-wrap  justify-end  bg-green-200'>
            <motion.div className='pr-10'>ico</motion.div>
            <motion.div className='pr-10'>singiin</motion.div>
            <motion.div className=''>singiup</motion.div>
          </motion.div>
        </motion.div>
        <motion.div>
          <Tab />
        </motion.div>
        {/* one */}
        <motion.div
          animate={{ opacity: 0 }}
          transition={{ ease: [0.17, 0.67, 0.83, 0.67] }}
          className='bg-red-300 mt-40 m-5 text-center  grid h-1/3 grid-cols-4 gap-10 p-20 '
        >
          <motion.div className='bg-gray-200'>one</motion.div>
          <motion.div className=' bg-green-200'>tow</motion.div>
          <motion.div className='bg-slate-200'>three</motion.div>
          <motion.div className='bg-green-200'>four</motion.div>
        </motion.div>

        {/* two */}
        <motion.div className='m-5 mt-40'>
          <motion.div className='bg-gray-200 mt-10 p-10'>one</motion.div>
          <motion.div className=' bg-green-200 mt-10 p-10'>tow</motion.div>
          <motion.div className='bg-slate-200 mt-10 p-10'>three</motion.div>
          <motion.div className='bg-green-200 mt-10 p-10'>four</motion.div>
        </motion.div>
        {/* img */}
        <motion.div className=' m-40 text-center'>
          <AnimatePresence>
            <motion.img
              // key={}
              // src={}
              initial={{ opacity: 0, y: 200 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            />
          </AnimatePresence>
          {/* <Image src='/1.jpg' layout='fixed' width={'1000px'} height='500px' /> */}
        </motion.div>
        {/* three */}
        <motion.div className='m-5 mt-40'>
          <motion.div className='bg-gray-200 mt-10 p-10'>one</motion.div>
          <motion.div className=' bg-green-200 mt-10 p-10'>tow</motion.div>
          <motion.div className='bg-slate-200 mt-10 p-10'>three</motion.div>
          <motion.div className='bg-green-200 mt-10 p-10'>four</motion.div>
        </motion.div>
        {/* four */}
        <motion.div className='bg-red-300 mt-40 m-5 text-center  grid h-1/3 grid-cols-4 gap-10 p-20 '>
          <motion.div className='bg-gray-200'>one</motion.div>
          <motion.div className=' bg-green-200'>tow</motion.div>
          <motion.div className='bg-slate-200'>three</motion.div>
          <motion.div className='bg-green-200'>four</motion.div>
        </motion.div>
        {/* img2 */}
        <motion.div className=' m-40 text-center'>
          <Image src='/1.jpg' layout='fixed' width={'1000px'} height='500px' />
        </motion.div>
        {/* footer */}
        <motion.div className='m-5 mt-40'>
          <motion.div className='bg-gray-200 mt-10 p-10'>one</motion.div>
          <motion.div className=' bg-green-200 mt-10 p-10'>tow</motion.div>
          <motion.div className='bg-slate-200 mt-10 p-10'>three</motion.div>
          <motion.div className='bg-green-200 mt-10 p-10'>four</motion.div>
        </motion.div>
      </main>
      <footer className='text-center p-2'>footer</footer>
    </>
  )
}

export default Home
